### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Robert-W** [blueraster/esri-canvas-tile#4]
Here are some todos to enhance this layer:
- [ ] Rewrite in ES6
- [ ] Make more modular so it is easier to extend
- [ ] Add testing of some sort, at minimum eslint
  - [ ] Flowtype?
  - [ ] Unit Tests with Mocha & Chai?
